In [66]:
using Plots, DataFrames, CSV, Measures, Dates

In [2]:
f = joinpath(homedir(), "research", "GADS_Processed", "aggregate_texas", "texas_available_capacity_pct_by_unit_type.csv")
pct_offline = DataFrame(CSV.File(f))

96409×14 DataFrame
   Row │ 861       851      300      852       100      650      850      500  ⋯
       │ Float64   Float64  Float64  Float64   Float64  Float64  Float64  Floa ⋯
───────┼────────────────────────────────────────────────────────────────────────
     1 │  4.87805  7.14286  5.95238   7.89474  14.2857      0.0  3.0303   33.3 ⋯
     2 │  4.87805  7.14286  5.95238   7.89474  14.2857      0.0  3.0303   33.3
     3 │  4.87805  7.14286  5.95238   7.89474  14.2857      0.0  3.0303   33.3
     4 │  4.87805  7.14286  5.95238   7.89474  14.2857      0.0  3.0303   33.3
     5 │  4.87805  7.14286  5.95238   7.89474  14.2857      0.0  3.0303   33.3 ⋯
     6 │  4.87805  7.14286  5.95238   7.89474  15.0794      0.0  3.0303   33.3
     7 │  4.87805  7.14286  5.95238   7.89474  14.2857      0.0  3.0303   33.3
     8 │  4.87805  7.14286  5.95238   7.89474  14.2857      0.0  3.0303   33.3
   ⋮   │    ⋮         ⋮        ⋮        ⋮         ⋮        ⋮        ⋮        ⋮ ⋱
 96403 │ 22.7273   5.45455  4.26829  11.5385   31.5789     40.0  9.67742  13.3 ⋯
 96404 │ 22.7273   5.45455  4.26829  11.5385   31.5789     40.0  9.67742  13.3
 96405 │ 22.7273   5.45455  4.26829  11.5385   31.5789     40.0  9.67742  13.3
 96406 │ 22.7273   5.45455  4.26829  11.5385   31.5789     40.0  9.67742  13.3
 96407 │ 22.7273   4.54545  4.26829   9.61538  31.5789     40.0  9.67742  13.3 ⋯
 96408 │ 22.7273   4.54545  4.26829   9.61538  31.5789     40.0  9.67742  13.3
 96409 │ 22.7273   4.54545  4.26829   9.61538  31.5789     40.0  9.67742  13.3
                                                7 columns and 96394 rows omitted

In [ ]:
label = [861	851	300	852	100	650	850	500	200	800	860	862	400]
colnames = Symbol.(reshape(label, (13,)))
code_dict = Dict([(100, "Fossil-Steam"), (200, "Nuclear"), (300, "Gas Turbine/Jet Engine"), (400, "Internal Combustion Engines"), (500, "Pumped Storage/Hydro"), (650, "Fluidized Bed"), (800, "Miscellaneous"), (810, "Multi-boiler/Multi-turbine"), (830, "Geothermal"), (850, "Combined Cycle Block"), (851, "CC GT units"), (852, "CC steam units"), (860, "Co-generator block"), (861, "CoG CT units"), (862, "CoG steam units")])
str_label = map(k -> code_dict[k], label)

13-element Vector{Symbol}:
 Symbol("861")
 Symbol("851")
 Symbol("300")
 Symbol("852")
 Symbol("100")
 Symbol("650")
 Symbol("850")
 Symbol("500")
 Symbol("200")
 Symbol("800")
 Symbol("860")
 Symbol("862")
 Symbol("400")

In [15]:
y_matrix = Matrix(pct_offline[:, colnames])

96409×13 Matrix{Float64}:
  4.87805  7.14286  5.95238   7.89474  …  33.3333    0.0   9.09091  100.0
  4.87805  7.14286  5.95238   7.89474     33.3333    0.0   9.09091  100.0
  4.87805  7.14286  5.95238   7.89474     33.3333    0.0   9.09091  100.0
  4.87805  7.14286  5.95238   7.89474     33.3333    0.0   9.09091  100.0
  4.87805  7.14286  5.95238   7.89474     33.3333    0.0   9.09091  100.0
  4.87805  7.14286  5.95238   7.89474  …  33.3333    0.0   9.09091  100.0
  4.87805  7.14286  5.95238   7.89474     33.3333    0.0   9.09091  100.0
  4.87805  7.14286  5.95238   7.89474     33.3333    0.0   9.09091  100.0
  4.87805  7.14286  5.95238   7.89474     33.3333    0.0   9.09091  100.0
  4.87805  7.14286  5.95238   7.89474     33.3333    0.0   9.09091  100.0
  ⋮                                    ⋱             ⋮              
 22.7273   5.45455  4.26829  11.5385   …   0.0     100.0  33.3333    11.1111
 22.7273   5.45455  4.26829  11.5385       0.0     100.0  33.3333    11.1111
 22.7273   

In [29]:
default(; # Plots defaults
    fontfamily="Computer modern")

In [55]:
areaplot(pct_offline[1:8760, :x],  y_matrix[1:8760, :]./13, size=(800, 500), label=str_label, fillalpha = 0.4, palette=collect(cgrad(:batlow25, 13, categorical=true)), ylabel="% of Units Offline", title="Conventional Generators in Texas", legendtitle="Unit Type", xlabel="Date", legendfontsize=6, legend=:outerbottom, legendtitlefontsize=6, legend_column=3,leftmargin=4mm)
savefig("texas_all_types_available_capacity_2013.png")

"/home/emco4286/research/GADS_Processing_Scripts/texas_all_types_available_capacity_2013.png"

In [68]:
t = DateTime(2013, 1, 1):Year(1):DateTime(2024, 1, 1)
time_ticks = Dates.format.(t,"yyyy")

12-element Vector{String}:
 "2013"
 "2014"
 "2015"
 "2016"
 "2017"
 "2018"
 "2019"
 "2020"
 "2021"
 "2022"
 "2023"
 "2024"

In [70]:
areaplot(pct_offline[!, :x],  y_matrix[:, 5], label="", fillalpha = 0.4, ylabel="% of Units Offline", title="Fossil-Steam Units in Texas", xlabel="Date", xticks=(t, time_ticks))
savefig("texas_type_100_available_capacity.png")

"/home/emco4286/research/GADS_Processing_Scripts/texas_type_100_available_capacity.png"